── 1. Failure: Failure:1 (@tests.R#14)  ────────────────────────────────────────
Failure has been forced

── 2. Failure: Failure:2a (@tests.R#18)  ───────────────────────────────────────
Failure has been forced

── 3. Failure: Failure:2b (@tests.R#21)  ───────────────────────────────────────
FALSE isn't true.

── 4. Failure: Failure:loop (@tests.R#26)  ─────────────────────────────────────
`actual` (`i`) not equal to `expected` (2).

  `actual`: 1
`expected`: 2

── 5. Error: Error:1 (@tests.R#35)  ────────────────────────────────────────────
stop

── 6. Error: Error:3 (@tests.R#49)  ────────────────────────────────────────────
!
Backtrace:
 1. f()
 2. g()
 3. h()

── 7. Error: Recursion:1 (@tests.R#58)  ────────────────────────────────────────
This is deep
Backtrace:
  1. f(25)
  2. f(x - 1)
  3. f(x - 1)
  4. f(x - 1)
  5. f(x - 1)
  6. f(x - 1)
  7. f(x - 1)
  8. f(x - 1)
  9. f(x - 1)
 10. f(x - 1)
     ...
 17. f(x - 1)
 18. f(x - 1)
 19. f(x - 1)
 20. f(x - 1)
 21. f(x - 1)
 22. f(x - 1)
 23. f(x - 1)
 24. f(x - 1)
 25. f(x - 1)
 26. f(x - 1)

── 8. Error: Error:4 (@tests.R#113)  ───────────────────────────────────────────
Throwable

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 5 | SKIPPED: 3 | WARNINGS: 3 | FAILED: 8 ]
1. Failure: Failure:1 (@tests.R#14) 
2. Failure: Failure:2a (@tests.R#18) 
3. Failure: Failure:2b (@tests.R#21) 
4. Failure: Failure:loop (@tests.R#26) 
5. Error: Error:1 (@tests.R#35) 
6. Error: Error:3 (@tests.R#49) 
7. Error: Recursion:1 (@tests.R#58) 
8. Error: Error:4 (@tests.R#113) 

