✔ |  OK F W S | Context

⠏ |   0       | backtraces
⠋ |   0 1     | backtraces
⠙ |   0 2     | backtraces
⠹ |   0 3     | backtraces
⠸ |   0 4     | backtraces
⠼ |   0 5     | backtraces
⠴ |   0 6     | backtraces
⠦ |   0 7     | backtraces
✖ |   0 7     | backtraces
────────────────────────────────────────────────────────────────────────────────
backtraces.R:4: error: errors thrown at block level are entraced
foo
Backtrace:
 1. f()
 2. g()

backtraces.R:9: error: errors thrown from a quasi-labelled argument are entraced
foo
Backtrace:
 1. testthat::expect_s3_class(foo(), "foo")
 4. foo()

backtraces.R:16: error: errors thrown from a quasi-labelled argument are entraced (deep case)
foo
Backtrace:
 1. testthat::expect_s3_class(f(), "foo")
 4. f()
 5. g()
 9. foo()

backtraces.R:26: error: errors thrown from a quasi-labelled argument are entraced (deep deep case)
foobar
Backtrace:
 1. f()
 2. g()
 6. foo()
 7. bar()

backtraces.R:33: failure: failed expect_error() prints a backtrace
`f()` threw an condition with unexpected class.

Backtrace:
 1. testthat::expect_condition(f(), class = "foo")
 6. f()
 7. signaller()

backtraces.R:36: failure: failed expect_error() prints a backtrace
`f()` threw an error with unexpected message.
Expected match: "foo"
Actual message: "bar"
Backtrace:
 1. testthat::expect_error(f(), "foo")
 6. f()
 7. signaller()

backtraces.R:44: error: Errors are inspected with `conditionMessage()`
dispatched
────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════
OK:       0
Failed:   7
Warnings: 0
Skipped:  0
